# Introducción a la programación en R para analizar datos

  <img src="LogoNegativo.png"
     alt="Markdown Monster icon"
     style="float: left; margin-right: 10px;"
     height="200" width="200" align = "center" />
     
 Yubar Daniel Marín Benjumea 
 
 **Linkeding**  www.linkedin.com/in/ydmarinb
 
 **StatAsesores** https://www.facebook.com/StatAsesores-106875704170849/?modal=admin_todo_tour

## Tipos de datos en R

* **character** -> Cadena de texto.
* **numeric** -> Número continuo (Real).
* **integer** -> Número entero.
* **logical** -> Verdadero o falso.
* **factor** -> Categórico.
* **Date** -> Fecha

## Ficheros en R 

Un archivo o fichero informático es un conjunto de bytes que son almacenados en un dispositivo. (Wikipedia)

### Archivo de excel

In [6]:
library(readxl)
auto <- read_excel("Bases de datos/auto.xlsx", sheet = 2)
head(auto)

  No mpg cylinders displacement horsepower weight acceleration model_year
1 1  28  4         140          90         2264   15.5         71
2 2  19  3          70          97         2330   13.5         72
3 3  36  4         107          75         2205   14.5         82
4 4  28  4          97          92         2288   17.0         72
5 5  21  6         199          90         2648   15.0         70
6 6  23  4         115          95         2694   15.0         75
  car_name
1 chevrolet vega 2300
2 mazda rx2 coupe
3 honda accord
4 datsun 510 (sw)
5 amc gremlin
6 audi 100ls

### Archivo de csv

In [40]:
auto <- read.csv('Bases de datos/auto.csv')
head(auto)

  No mpg cylinders displacement horsepower weight acceleration model_year
1 1  28  4         140          90         2264   15.5         71
2 2  19  3          70          97         2330   13.5         72
3 3  36  4         107          75         2205   14.5         82
4 4  28  4          97          92         2288   17.0         72
5 5  21  6         199          90         2648   15.0         70
6 6  23  4         115          95         2694   15.0         75
  car_name
1 chevrolet vega 2300
2 mazda rx2 coupe
3 honda accord
4 datsun 510 (sw)
5 amc gremlin
6 audi 100ls

### Archivo de txt

In [8]:
auto <- read.delim('Bases de datos/auto.txt')
head(auto)

  No mpg cylinders displacement horsepower weight acceleration model_year
1 1  28  4         140          90         2264   15.5         71
2 2  19  3          70          97         2330   13.5         72
3 3  36  4         107          75         2205   14.5         82
4 4  28  4          97          92         2288   17.0         72
5 5  21  6         199          90         2648   15.0         70
6 6  23  4         115          95         2694   15.0         75
  car_name
1 chevrolet vega 2300
2 mazda rx2 coupe
3 honda accord
4 datsun 510 (sw)
5 amc gremlin
6 audi 100ls

### Archivo de txt raro

In [41]:
auto.corregir <- read.delim('Bases de datos/auto_corregir.txt', skip = 2, sep = "/", header = F,
                            na.strings = c('-', '&', ' ', 'NA'))
head(auto.corregir)

  V1 V2 V3 V4  V5 V6   V7   V8 V9
1 1  28 4  140 90 2264 15.5 71 chevrolet vega 2300
2 2  19 3   70 97 2330 13.5 72 mazda rx2 coupe
3 3  36 4  107 75 2205 14.5 82 honda accord
4 4  28 4   97 92 2288 17   72 datsun 510 (sw)
5 5  21 6  199 90 2648 15   70 amc gremlin
6 6  23 4  115 95 2694 15   75 audi 100ls

# Estructuras de datos

### Vectores

Los vectores son arreglos ordenados en los cuales se puede almacenar información numérica (Cuantitativa), alfanumérico (Cualitativa), booleano (True, false), o combinaciones de los anteriores. En R pueden ser creados por medio de la instrucción `c()`que significa concatenar o por medio de las funciones `rep()`, `seq()` y `:`que permiten la creación de patrones.

In [35]:
names(auto.corregir) <- c('No', 'mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
                          'acceleration', 'model_year', 'car_name')

In [36]:
head(auto.corregir)

  No mpg cylinders displacement horsepower weight acceleration model_year
1 1  28  4         140          90         2264   15.5         71
2 2  19  3          70          97         2330   13.5         72
3 3  36  4         107          75         2205   14.5         82
4 4  28  4          97          92         2288   17           72
5 5  21  6         199          90         2648   15           70
6 6  23  4         115          95         2694   15           75
  car_name
1 chevrolet vega 2300
2 mazda rx2 coupe
3 honda accord
4 datsun 510 (sw)
5 amc gremlin
6 audi 100ls

In [30]:
v1 <- 1:10 
v2 <- c(1, 3, 4)
v3 <- seq(from = 1, to = 7, by = 2)
v4 <- rep(4, 6)

In [31]:
print(v1)
print(v2)
print(v3)
print(v4)

 [1]  1  2  3  4  5  6  7  8  9 10
[1] 1 3 4
[1] 1 3 5 7
[1] 4 4 4 4 4 4

In [55]:
v1[1]

[1] 1

In [56]:
v1[-3]

[1]  1  2  4  5  6  7  8  9 10

### Data frames

Los data frame son estructuras de datos que permiten agrupar vectores diferentes tipos de datos (numérica, categórica, booleana) en un mismo objeto, pero que debe cumplir la condición de que todos los vectores deben tener la misma longitud. En R los data frame son generados por medio de la función `data.frame()`.

In [50]:
class(auto)

[1] "data.frame"

In [54]:
dim(auto)

[1] 398   9

In [60]:
x <- rep(2, dim(auto)[1])
x

  [1] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 [38] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 [75] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
[112] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
[149] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
[186] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
[223] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
[260] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
[297] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
[334] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
[371] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2

In [61]:
auto$nueva.columna <- x

In [62]:
head(auto)

  No mpg cylinders displacement horsepower weight acceleration model_year
1 1  28  4         140          90         2264   15.5         71
2 2  19  3          70          97         2330   13.5         72
3 3  36  4         107          75         2205   14.5         82
4 4  28  4          97          92         2288   17.0         72
5 5  21  6         199          90         2648   15.0         70
6 6  23  4         115          95         2694   15.0         75
  car_name            nueva.columna
1 chevrolet vega 2300 2
2 mazda rx2 coupe     2
3 honda accord        2
4 datsun 510 (sw)     2
5 amc gremlin         2
6 audi 100ls          2

In [63]:
auto[, 'nueva.columna1'] <- x

In [64]:
head(auto)

  No mpg cylinders displacement horsepower weight acceleration model_year
1 1  28  4         140          90         2264   15.5         71
2 2  19  3          70          97         2330   13.5         72
3 3  36  4         107          75         2205   14.5         82
4 4  28  4          97          92         2288   17.0         72
5 5  21  6         199          90         2648   15.0         70
6 6  23  4         115          95         2694   15.0         75
  car_name            nueva.columna nueva.columna1
1 chevrolet vega 2300 2             2
2 mazda rx2 coupe     2             2
3 honda accord        2             2
4 datsun 510 (sw)     2             2
5 amc gremlin         2             2
6 audi 100ls          2             2

In [66]:
auto <- auto[,-1]

In [67]:
head(auto)

  mpg cylinders displacement horsepower weight acceleration model_year
1 28  4         140          90         2264   15.5         71
2 19  3          70          97         2330   13.5         72
3 36  4         107          75         2205   14.5         82
4 28  4          97          92         2288   17.0         72
5 21  6         199          90         2648   15.0         70
6 23  4         115          95         2694   15.0         75
  car_name            nueva.columna nueva.columna1
1 chevrolet vega 2300 2             2
2 mazda rx2 coupe     2             2
3 honda accord        2             2
4 datsun 510 (sw)     2             2
5 amc gremlin         2             2
6 audi 100ls          2             2

In [68]:
auto$indicador <- seq(1, dim(auto)[1], 1 )

In [69]:
head(auto)

  mpg cylinders displacement horsepower weight acceleration model_year
1 28  4         140          90         2264   15.5         71
2 19  3          70          97         2330   13.5         72
3 36  4         107          75         2205   14.5         82
4 28  4          97          92         2288   17.0         72
5 21  6         199          90         2648   15.0         70
6 23  4         115          95         2694   15.0         75
  car_name            nueva.columna nueva.columna1 indicador
1 chevrolet vega 2300 2             2              1
2 mazda rx2 coupe     2             2              2
3 honda accord        2             2              3
4 datsun 510 (sw)     2             2              4
5 amc gremlin         2             2              5
6 audi 100ls          2             2              6

In [72]:
auto <- auto[, -c(9, 10)]
head(auto)

  mpg cylinders displacement horsepower weight acceleration model_year
1 28  4         140          90         2264   15.5         71
2 19  3          70          97         2330   13.5         72
3 36  4         107          75         2205   14.5         82
4 28  4          97          92         2288   17.0         72
5 21  6         199          90         2648   15.0         70
6 23  4         115          95         2694   15.0         75
  car_name            indicador
1 chevrolet vega 2300 1
2 mazda rx2 coupe     2
3 honda accord        3
4 datsun 510 (sw)     4
5 amc gremlin         5
6 audi 100ls          6

# Recodificar datos

In [77]:
auto$cylinders <- as.factor(auto$cylinders)
auto$car_name <- as.character(auto$car_name)
auto$model_year <- as.factor(auto$model_year)

In [78]:
head(auto)

  mpg cylinders displacement horsepower weight acceleration model_year
1 28  4         140          90         2264   15.5         71
2 19  3          70          97         2330   13.5         72
3 36  4         107          75         2205   14.5         82
4 28  4          97          92         2288   17.0         72
5 21  6         199          90         2648   15.0         70
6 23  4         115          95         2694   15.0         75
  car_name            indicador
1 chevrolet vega 2300 1
2 mazda rx2 coupe     2
3 honda accord        3
4 datsun 510 (sw)     4
5 amc gremlin         5
6 audi 100ls          6

In [83]:
print(paste('1', 'a'))

[1] "1 a"

In [84]:
print(paste(1:10, 'a'))

 [1] "1 a"  "2 a"  "3 a"  "4 a"  "5 a"  "6 a"  "7 a"  "8 a"  "9 a"  "10 a"

In [80]:
levels(auto$cylinders)

[1] "3" "4" "5" "6" "8"

In [81]:
auto$cylinders <- factor(auto$cylinders,levels(auto$cylinders), labels = paste(levels(auto$cylinders), ' cyliders') )

In [82]:
head(auto)

  mpg cylinders   displacement horsepower weight acceleration model_year
1 28  4  cyliders 140          90         2264   15.5         71
2 19  3  cyliders  70          97         2330   13.5         72
3 36  4  cyliders 107          75         2205   14.5         82
4 28  4  cyliders  97          92         2288   17.0         72
5 21  6  cyliders 199          90         2648   15.0         70
6 23  4  cyliders 115          95         2694   15.0         75
  car_name            indicador
1 chevrolet vega 2300 1
2 mazda rx2 coupe     2
3 honda accord        3
4 datsun 510 (sw)     4
5 amc gremlin         5
6 audi 100ls          6

$$\frac{LimiteSuperior - LimiteInferior}{2}$$

In [99]:
range(auto$weight)

[1] 1613 5140

In [100]:
punto.corte <- (range(auto$weight)[2] +  range(auto$weight)[1]) / 2

In [104]:
auto$weight <= punto.corte

  [1]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE FALSE FALSE  TRUE
 [13] FALSE  TRUE FALSE  TRUE  TRUE FALSE FALSE  TRUE FALSE  TRUE  TRUE  TRUE
 [25]  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE FALSE
 [37]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE FALSE
 [49] FALSE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE FALSE FALSE
 [61]  TRUE  TRUE FALSE FALSE FALSE  TRUE  TRUE FALSE FALSE FALSE  TRUE  TRUE
 [73]  TRUE  TRUE FALSE FALSE  TRUE  TRUE FALSE FALSE  TRUE  TRUE  TRUE  TRUE
 [85]  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE FALSE  TRUE  TRUE  TRUE  TRUE
 [97]  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE FALSE
[109]  TRUE  TRUE  TRUE FALSE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE
[121]  TRUE FALSE FALSE  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE
[133] FALSE FALSE FALSE  TRUE  TRUE  TRUE FALSE FALSE FALSE  TRUE FALSE  TRUE
[145] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE
[157] FALSE FALSE  TRUE  TRUE  TRUE  TRUE FALSE FALSE  TRUE FALSE FALSE  TRUE
[169]  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE
[181]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE  TRUE  TRUE FALSE  TRUE  TRUE
[193] FALSE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[205]  TRUE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE
[217]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
[229]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE FALSE
[241]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE FALSE
[253] FALSE FALSE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[265]  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE  TRUE FALSE FALSE  TRUE  TRUE
[277] FALSE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE
[289]  TRUE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[301]  TRUE  TRUE  TRUE  TRUE FALSE FALSE  TRUE  TRUE  TRUE FALSE FALSE  TRUE
[313]  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE FALSE FALSE  TRUE  TRUE  TRUE
[325]  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE
[337]  TRUE  TRUE  TRUE FALSE FALSE  TRUE  TRUE FALSE FALSE  TRUE FALSE  TRUE
[349]  TRUE FALSE  TRUE  TRUE  TRUE FALSE  TRUE FALSE FALSE FALSE  TRUE  TRUE
[361]  TRUE FALSE FALSE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE
[373]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE
[385] FALSE  TRUE FALSE  TRUE FALSE FALSE  TRUE  TRUE FALSE FALSE  TRUE  TRUE
[397]  TRUE  TRUE

In [105]:
auto$peso.categoria <- auto$weight <= punto.corte

In [106]:
head(auto)

  mpg cylinders   displacement horsepower weight acceleration model_year
1 28  4  cyliders 140          90         2264   15.5         71
2 19  3  cyliders  70          97         2330   13.5         72
3 36  4  cyliders 107          75         2205   14.5         82
4 28  4  cyliders  97          92         2288   17.0         72
5 21  6  cyliders 199          90         2648   15.0         70
6 23  4  cyliders 115          95         2694   15.0         75
  car_name            indicador peso.categoria
1 chevrolet vega 2300 1         TRUE
2 mazda rx2 coupe     2         TRUE
3 honda accord        3         TRUE
4 datsun 510 (sw)     4         TRUE
5 amc gremlin         5         TRUE
6 audi 100ls          6         TRUE

In [107]:
auto$peso.categoria <- factor(auto$peso.categoria, c(T, F), c('Bajo', 'Alto'))

In [108]:
head(auto)

  mpg cylinders   displacement horsepower weight acceleration model_year
1 28  4  cyliders 140          90         2264   15.5         71
2 19  3  cyliders  70          97         2330   13.5         72
3 36  4  cyliders 107          75         2205   14.5         82
4 28  4  cyliders  97          92         2288   17.0         72
5 21  6  cyliders 199          90         2648   15.0         70
6 23  4  cyliders 115          95         2694   15.0         75
  car_name            indicador peso.categoria
1 chevrolet vega 2300 1         Bajo
2 mazda rx2 coupe     2         Bajo
3 honda accord        3         Bajo
4 datsun 510 (sw)     4         Bajo
5 amc gremlin         5         Bajo
6 audi 100ls          6         Bajo

# Subconjuntos de datos

In [113]:
auto.4cilindros <- auto[auto$cylinders == '4  cyliders', ]
head(auto.4cilindros)

   mpg  cylinders   displacement horsepower weight acceleration model_year
1  28.0 4  cyliders 140           90        2264   15.5         71
3  36.0 4  cyliders 107           75        2205   14.5         82
4  28.0 4  cyliders  97           92        2288   17.0         72
6  23.0 4  cyliders 115           95        2694   15.0         75
8  32.9 4  cyliders 119          100        2615   14.8         81
14 27.9 4  cyliders 156          105        2800   14.4         80
   car_name            indicador peso.categoria
1  chevrolet vega 2300  1        Bajo
3  honda accord         3        Bajo
4  datsun 510 (sw)      4        Bajo
6  audi 100ls           6        Bajo
8  datsun 200sx         8        Bajo
14 dodge colt          14        Bajo

### Operadores 

* **x | y** <- Operador O

* **x & y** <- OPerador Y

* **!x** <- Negación

* **isTRUE(x)** <- X es verdad?

* **==** <- Comparación

* **<, < =, >, > =** <- Mayor, Mayor o igual, Menor y Menor o igual.

* **%in%** <- Permite determinar si uno o varios valores están contenidos en un vector.

In [124]:
auto[auto$mpg > 40, c(1,5)]

    mpg  weight
27  40.8 2110
87  40.9 1835
95  43.4 2335
144 41.5 2144
150 44.0 2130
263 43.1 1985
269 46.6 2110
335 44.3 2085
388 44.6 1850